name: main
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'
jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: jedrzejginter/create-react-project-app-01
          path: create-react-project-app-01
          ref: main
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4

      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn global cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Restore node_modules cache for repository
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-root-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-root-node-modules-

      - run: yarn --pure-lockfile --ignore-optional
      - run: (cd with-tailwind && yarn)
      - run: yarn lint

      - name: Create basic project
        uses: ./.github/actions/build-and-test-project
        with:
          out: new-project
          name: create-react-project-app-01
          cli-flags: '--force'

      - name: Create project with Tailwind
        uses: ./.github/actions/build-and-test-project
        with:
          out: create-react-project-with-tailwind
          name: create-react-project-with-tailwind
          cli-flags: '--withTailwind'

      - name: Create commit with changes to generated project
        id: git-commit
        run: |
          cp -R create-react-project-app-01/.git new-project/.git
          rm -rf create-react-project-app-01
          mv new-project create-react-project-app-01
          cd create-react-project-app-01
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "[gh-actions] Push new version of the project" && \
            echo "::set-output name=should-push::true"

      - if: steps.git-commit.outputs.should-push != 'true'
        run: echo ${{ steps.git-commit.outputs.should-push }}

      # Sync only for "main" branch.
      - name: Sync created project with external repo
        if: github.ref == 'refs/heads/main' && steps.git-commit.outputs.should-push == 'true'
        run: |
          cd create-react-project-app-01
          git push -f
