name: main
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'
jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: jedrzejginter/create-react-project-app-01
          path: create-react-project-app-01
          ref: main
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4

      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn global cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Restore node_modules cache for repository
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-root-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-root-node-modules-

      - run: yarn --pure-lockfile --ignore-optional
      - run: node build/cli.js --out new-project --name create-react-project-app-01 --force

      # Run check in output project
      - run: (cd new-project && yarn typecheck)
      - run: (cd new-project && yarn test --ci)

      - run: PROJECT_OUT=new-project PROJECT_NAME=create-react-project-app-01 yarn test --ci

      # Sync only for "main" branch.
      - name: Sync created project with external repo
        # if: github.ref == 'refs/heads/main'
        run: |
          cp -R create-react-project-app-01/.git new-project/.git
          rm -rf create-react-project-app-01
          mv new-project create-react-project-app-01
          cd create-react-project-app-01
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "${{ github.event.head_commit.message }}""
          git push -f
