name: sync
on:
  push:
    branches: ['feat/sync']
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source
      - name: Checkout target
        uses: actions/checkout@v2
        with:
          repository: jedrzejginter/crp-test-v2
          path: target
          ref: main
          token: ${{ secrets.PAT }}

      - run: date > target/generated.txt
      - run: |
          cd target
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated.txt
          git commit -m 'test commit'
          git remote add source git@github.com:jedrzejginter/crp-test-v2.git
          git push -f source main

