name: "build and test project"
inputs:
  test-task:
    required: true
  cli-input:
    required: true
runs:
  using: "composite"
  steps:
    - run: node build/cli.js ${{ inputs.cli-flags }}
      shell: bash
    - run: ./test.sh ${{ input.test-task }}
      shell: bash
    - run: (cd out && yarn typecheck)
      shell: bash
    - run: (cd out && yarn test --ci)
      shell: bash
